name: Basic Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check files
        run: ls -la

      - name: Print message
        run: echo "GitHub Actions is working successfully!"
